### ISSUE TITLE
打包安装后打开报错

### ISSUE THREAD

**Issue by asdf12343800** [sweetwisdom/elecreon-ffmpeg#1]
![image](https://user-images.githubusercontent.com/4454416/211442250-2a236c60-1e38-4577-8111-8c3f09217f38.png)
你好，作者。
我运行yarn build，
打包安装后打开桌面上的图标报错了，出现上图中的错误，是windows 10系统

**Comment by sweetwisdom** [comment]
你好,进入项目public 目录,执行`npm i `,再打包试试
![image](https://user-images.githubusercontent.com/57869305/211452597-e137cfff-2c03-41f2-bf7e-9feee886834c.png)

**Comment by asdf12343800** [comment]
解决了，感谢回复
